const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");

const root = resolve(__dirname, "..");
const specPath = resolve(root, "shared", "shared_state_spec.json");
const spec = JSON.parse(readFileSync(specPath, "utf-8"));

// Rust module (also generated by memio-core/build.rs at compile time)
const rustModule = `// Generated from shared/shared_state_spec.json. Do not edit by hand.
pub const SHARED_STATE_MAGIC: u64 = ${spec.magic_hex};
pub const SHARED_STATE_HEADER_SIZE: usize = ${spec.header_size};
pub const SHARED_STATE_MAGIC_OFFSET: usize = ${spec.offsets.magic};
pub const SHARED_STATE_VERSION_OFFSET: usize = ${spec.offsets.version};
pub const SHARED_STATE_LENGTH_OFFSET: usize = ${spec.offsets.length};
pub const SHARED_STATE_ENDIANNESS: &str = "${spec.endianness}";
`;

// TypeScript module
const tsModule = `// Generated from shared/shared_state_spec.json. Do not edit by hand.
export const SHARED_STATE_MAGIC = ${spec.magic_hex}n;
export const SHARED_STATE_HEADER_SIZE = ${spec.header_size};
export const SHARED_STATE_MAGIC_OFFSET = ${spec.offsets.magic};
export const SHARED_STATE_VERSION_OFFSET = ${spec.offsets.version};
export const SHARED_STATE_LENGTH_OFFSET = ${spec.offsets.length};
export const SHARED_STATE_ENDIANNESS = "${spec.endianness}" as const;
`;

// C header for WebKit extension
const cHeader = `// Generated from shared/shared_state_spec.json. Do not edit by hand.
// This header ensures the WebKit extension uses the same constants as Rust.

#ifndef MEMIO_SHARED_STATE_SPEC_H
#define MEMIO_SHARED_STATE_SPEC_H

#include <stdint.h>

#define MEMIO_MAGIC ${spec.magic_hex}ULL
#define MEMIO_HEADER_SIZE ${spec.header_size}
#define MEMIO_MAGIC_OFFSET ${spec.offsets.magic}
#define MEMIO_VERSION_OFFSET ${spec.offsets.version}
#define MEMIO_LENGTH_OFFSET ${spec.offsets.length}

// Endianness: ${spec.endianness}
// Multi-byte values are stored in ${spec.endianness}-endian format

#endif // MEMIO_SHARED_STATE_SPEC_H
`;

// Kotlin constants for Android
const kotlinConstants = `// Generated from shared/shared_state_spec.json. Do not edit by hand.
// This file ensures Android uses the same constants as Rust.

package com.memio.spec

object MemioSpec {
    const val MAGIC: Long = ${spec.magic_hex}L
    const val HEADER_SIZE: Int = ${spec.header_size}
    const val MAGIC_OFFSET: Int = ${spec.offsets.magic}
    const val VERSION_OFFSET: Int = ${spec.offsets.version}
    const val LENGTH_OFFSET: Int = ${spec.offsets.length}
    const val ENDIANNESS: String = "${spec.endianness}"
}
`;

const manifestSpecPath = resolve(root, "shared", "shared_manifest_spec.json");
const manifestSpec = JSON.parse(readFileSync(manifestSpecPath, "utf-8"));
const manifestTsModule = `// Generated from shared/shared_manifest_spec.json. Do not edit by hand.
export const SHARED_MANIFEST_VERSION = ${manifestSpec.version};
`;

// Write all generated files
writeFileSync(
  resolve(root, "crates", "memio-core", "src", "shared_state_spec.rs"),
  rustModule
);
writeFileSync(
  resolve(root, "packages", "memio-client", "src", "shared-state-spec.ts"),
  tsModule
);
writeFileSync(
  resolve(root, "packages", "memio-client", "src", "shared-manifest-spec.ts"),
  manifestTsModule
);
writeFileSync(
  resolve(root, "extensions", "webkit-linux", "memio_spec.h"),
  cHeader
);
writeFileSync(
  resolve(root, "crates", "tauri-plugin-memio", "android", "src", "main", "java", "com", "memio", "spec", "MemioSpec.kt"),
  kotlinConstants
);
console.log("✅ Generated shared state spec files:");
console.log("   - crates/memio-core/src/shared_state_spec.rs");
console.log("   - packages/memio-client/src/shared-state-spec.ts");
console.log("   - packages/memio-client/src/shared-manifest-spec.ts");
console.log("   - extensions/webkit-linux/memio_spec.h");
console.log("   - crates/tauri-plugin-memio/android/.../spec/MemioSpec.kt");
